name: CI/CD Pipeline for Spring Boot Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rouvsen-job:
    name: Build, Test, and Deploy Spring Boot App
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: get_short_sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'maven'

      - name: Build App (Skip Tests)
        run: |
          mvn clean install -DskipTests
        env:
          CI: true

      - name: Run Unit and Integration Tests
        run: |
          mvn test
          mvn verify

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/actions-app:${{ env.SHORT_SHA }}

      - name: Notify Deployment Status
        if: failure()
        run: echo "Build failed, please check the logs!"